//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessment6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dish
    {
        public int DishID { get; set; }
        public string DishName { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public string Email { get; set; }
    
        public virtual Guest Guest { get; set; }
    }
}
